# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/luca-phd/ros_ws/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/luca-phd/ros_ws/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/luca-phd/ros_ws/src && $(CMAKE_COMMAND) -E cmake_progress_start /home/luca-phd/ros_ws/src/CMakeFiles /home/luca-phd/ros_ws/src/primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/progress.marks
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/luca-phd/ros_ws/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/luca-phd/ros_ws/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/rule

# Convenience name for target.
clusterSegmentationSrv: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/rule
.PHONY : clusterSegmentationSrv

# fast build rule for target.
clusterSegmentationSrv/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build
.PHONY : clusterSegmentationSrv/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/rule

# Convenience name for target.
coneSegmentationSrv: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/rule
.PHONY : coneSegmentationSrv

# fast build rule for target.
coneSegmentationSrv/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build
.PHONY : coneSegmentationSrv/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/rule

# Convenience name for target.
cylinderSegmentationSrv: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/rule
.PHONY : cylinderSegmentationSrv

# fast build rule for target.
cylinderSegmentationSrv/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build
.PHONY : cylinderSegmentationSrv/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/rule

# Convenience name for target.
deepFilterSrv: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/rule
.PHONY : deepFilterSrv

# fast build rule for target.
deepFilterSrv/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/build
.PHONY : deepFilterSrv/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/rule

# Convenience name for target.
obj_segmentation: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/rule
.PHONY : obj_segmentation

# fast build rule for target.
obj_segmentation/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/build
.PHONY : obj_segmentation/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/rule

# Convenience name for target.
pcl_arm_filter_srv: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/rule
.PHONY : pcl_arm_filter_srv

# fast build rule for target.
pcl_arm_filter_srv/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/build
.PHONY : pcl_arm_filter_srv/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/rule

# Convenience name for target.
planeSegmentationSrv: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/rule
.PHONY : planeSegmentationSrv

# fast build rule for target.
planeSegmentationSrv/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build
.PHONY : planeSegmentationSrv/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/rule

# Convenience name for target.
ransac_segmentation: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/rule
.PHONY : ransac_segmentation

# fast build rule for target.
ransac_segmentation/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/build
.PHONY : ransac_segmentation/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/rule

# Convenience name for target.
sphereSegmentationSrv: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/rule
.PHONY : sphereSegmentationSrv

# fast build rule for target.
sphereSegmentationSrv/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build
.PHONY : sphereSegmentationSrv/fast

# Convenience name for target.
primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/rule:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f CMakeFiles/Makefile2 primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/rule
.PHONY : primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/rule

# Convenience name for target.
supportsSegmentationSrv: primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/rule
.PHONY : supportsSegmentationSrv

# fast build rule for target.
supportsSegmentationSrv/fast:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build
.PHONY : supportsSegmentationSrv/fast

src/PCStaticProcessing/PCManager.o: src/PCStaticProcessing/PCManager.cpp.o
.PHONY : src/PCStaticProcessing/PCManager.o

# target to build an object file
src/PCStaticProcessing/PCManager.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.o
.PHONY : src/PCStaticProcessing/PCManager.cpp.o

src/PCStaticProcessing/PCManager.i: src/PCStaticProcessing/PCManager.cpp.i
.PHONY : src/PCStaticProcessing/PCManager.i

# target to preprocess a source file
src/PCStaticProcessing/PCManager.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.i
.PHONY : src/PCStaticProcessing/PCManager.cpp.i

src/PCStaticProcessing/PCManager.s: src/PCStaticProcessing/PCManager.cpp.s
.PHONY : src/PCStaticProcessing/PCManager.s

# target to generate assembly for a file
src/PCStaticProcessing/PCManager.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/PCStaticProcessing/PCManager.cpp.s
.PHONY : src/PCStaticProcessing/PCManager.cpp.s

src/PCStaticProcessing/PCPrimitive.o: src/PCStaticProcessing/PCPrimitive.cpp.o
.PHONY : src/PCStaticProcessing/PCPrimitive.o

# target to build an object file
src/PCStaticProcessing/PCPrimitive.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.o
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.o
.PHONY : src/PCStaticProcessing/PCPrimitive.cpp.o

src/PCStaticProcessing/PCPrimitive.i: src/PCStaticProcessing/PCPrimitive.cpp.i
.PHONY : src/PCStaticProcessing/PCPrimitive.i

# target to preprocess a source file
src/PCStaticProcessing/PCPrimitive.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.i
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.i
.PHONY : src/PCStaticProcessing/PCPrimitive.cpp.i

src/PCStaticProcessing/PCPrimitive.s: src/PCStaticProcessing/PCPrimitive.cpp.s
.PHONY : src/PCStaticProcessing/PCPrimitive.s

# target to generate assembly for a file
src/PCStaticProcessing/PCPrimitive.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.s
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/PCStaticProcessing/PCPrimitive.cpp.s
.PHONY : src/PCStaticProcessing/PCPrimitive.cpp.s

src/SegmentationServices/clusterSegmentationServer.o: src/SegmentationServices/clusterSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/clusterSegmentationServer.o

# target to build an object file
src/SegmentationServices/clusterSegmentationServer.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/SegmentationServices/clusterSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/clusterSegmentationServer.cpp.o

src/SegmentationServices/clusterSegmentationServer.i: src/SegmentationServices/clusterSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/clusterSegmentationServer.i

# target to preprocess a source file
src/SegmentationServices/clusterSegmentationServer.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/SegmentationServices/clusterSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/clusterSegmentationServer.cpp.i

src/SegmentationServices/clusterSegmentationServer.s: src/SegmentationServices/clusterSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/clusterSegmentationServer.s

# target to generate assembly for a file
src/SegmentationServices/clusterSegmentationServer.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/clusterSegmentationSrv.dir/src/SegmentationServices/clusterSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/clusterSegmentationServer.cpp.s

src/SegmentationServices/coneSegmentationServer.o: src/SegmentationServices/coneSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/coneSegmentationServer.o

# target to build an object file
src/SegmentationServices/coneSegmentationServer.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/SegmentationServices/coneSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/coneSegmentationServer.cpp.o

src/SegmentationServices/coneSegmentationServer.i: src/SegmentationServices/coneSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/coneSegmentationServer.i

# target to preprocess a source file
src/SegmentationServices/coneSegmentationServer.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/SegmentationServices/coneSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/coneSegmentationServer.cpp.i

src/SegmentationServices/coneSegmentationServer.s: src/SegmentationServices/coneSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/coneSegmentationServer.s

# target to generate assembly for a file
src/SegmentationServices/coneSegmentationServer.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/coneSegmentationSrv.dir/src/SegmentationServices/coneSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/coneSegmentationServer.cpp.s

src/SegmentationServices/cylinderSegmentationServer.o: src/SegmentationServices/cylinderSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/cylinderSegmentationServer.o

# target to build an object file
src/SegmentationServices/cylinderSegmentationServer.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/SegmentationServices/cylinderSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/cylinderSegmentationServer.cpp.o

src/SegmentationServices/cylinderSegmentationServer.i: src/SegmentationServices/cylinderSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/cylinderSegmentationServer.i

# target to preprocess a source file
src/SegmentationServices/cylinderSegmentationServer.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/SegmentationServices/cylinderSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/cylinderSegmentationServer.cpp.i

src/SegmentationServices/cylinderSegmentationServer.s: src/SegmentationServices/cylinderSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/cylinderSegmentationServer.s

# target to generate assembly for a file
src/SegmentationServices/cylinderSegmentationServer.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/cylinderSegmentationSrv.dir/src/SegmentationServices/cylinderSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/cylinderSegmentationServer.cpp.s

src/SegmentationServices/deepFilterServer.o: src/SegmentationServices/deepFilterServer.cpp.o
.PHONY : src/SegmentationServices/deepFilterServer.o

# target to build an object file
src/SegmentationServices/deepFilterServer.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/src/SegmentationServices/deepFilterServer.cpp.o
.PHONY : src/SegmentationServices/deepFilterServer.cpp.o

src/SegmentationServices/deepFilterServer.i: src/SegmentationServices/deepFilterServer.cpp.i
.PHONY : src/SegmentationServices/deepFilterServer.i

# target to preprocess a source file
src/SegmentationServices/deepFilterServer.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/src/SegmentationServices/deepFilterServer.cpp.i
.PHONY : src/SegmentationServices/deepFilterServer.cpp.i

src/SegmentationServices/deepFilterServer.s: src/SegmentationServices/deepFilterServer.cpp.s
.PHONY : src/SegmentationServices/deepFilterServer.s

# target to generate assembly for a file
src/SegmentationServices/deepFilterServer.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/deepFilterSrv.dir/src/SegmentationServices/deepFilterServer.cpp.s
.PHONY : src/SegmentationServices/deepFilterServer.cpp.s

src/SegmentationServices/pcl_arm_filter_srv.o: src/SegmentationServices/pcl_arm_filter_srv.cpp.o
.PHONY : src/SegmentationServices/pcl_arm_filter_srv.o

# target to build an object file
src/SegmentationServices/pcl_arm_filter_srv.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/src/SegmentationServices/pcl_arm_filter_srv.cpp.o
.PHONY : src/SegmentationServices/pcl_arm_filter_srv.cpp.o

src/SegmentationServices/pcl_arm_filter_srv.i: src/SegmentationServices/pcl_arm_filter_srv.cpp.i
.PHONY : src/SegmentationServices/pcl_arm_filter_srv.i

# target to preprocess a source file
src/SegmentationServices/pcl_arm_filter_srv.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/src/SegmentationServices/pcl_arm_filter_srv.cpp.i
.PHONY : src/SegmentationServices/pcl_arm_filter_srv.cpp.i

src/SegmentationServices/pcl_arm_filter_srv.s: src/SegmentationServices/pcl_arm_filter_srv.cpp.s
.PHONY : src/SegmentationServices/pcl_arm_filter_srv.s

# target to generate assembly for a file
src/SegmentationServices/pcl_arm_filter_srv.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/pcl_arm_filter_srv.dir/src/SegmentationServices/pcl_arm_filter_srv.cpp.s
.PHONY : src/SegmentationServices/pcl_arm_filter_srv.cpp.s

src/SegmentationServices/planeSegmentationServer.o: src/SegmentationServices/planeSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/planeSegmentationServer.o

# target to build an object file
src/SegmentationServices/planeSegmentationServer.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/SegmentationServices/planeSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/planeSegmentationServer.cpp.o

src/SegmentationServices/planeSegmentationServer.i: src/SegmentationServices/planeSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/planeSegmentationServer.i

# target to preprocess a source file
src/SegmentationServices/planeSegmentationServer.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/SegmentationServices/planeSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/planeSegmentationServer.cpp.i

src/SegmentationServices/planeSegmentationServer.s: src/SegmentationServices/planeSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/planeSegmentationServer.s

# target to generate assembly for a file
src/SegmentationServices/planeSegmentationServer.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/planeSegmentationSrv.dir/src/SegmentationServices/planeSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/planeSegmentationServer.cpp.s

src/SegmentationServices/sphereSegmentationServer.o: src/SegmentationServices/sphereSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/sphereSegmentationServer.o

# target to build an object file
src/SegmentationServices/sphereSegmentationServer.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/SegmentationServices/sphereSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/sphereSegmentationServer.cpp.o

src/SegmentationServices/sphereSegmentationServer.i: src/SegmentationServices/sphereSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/sphereSegmentationServer.i

# target to preprocess a source file
src/SegmentationServices/sphereSegmentationServer.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/SegmentationServices/sphereSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/sphereSegmentationServer.cpp.i

src/SegmentationServices/sphereSegmentationServer.s: src/SegmentationServices/sphereSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/sphereSegmentationServer.s

# target to generate assembly for a file
src/SegmentationServices/sphereSegmentationServer.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/sphereSegmentationSrv.dir/src/SegmentationServices/sphereSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/sphereSegmentationServer.cpp.s

src/SegmentationServices/supportsSegmentationServer.o: src/SegmentationServices/supportsSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/supportsSegmentationServer.o

# target to build an object file
src/SegmentationServices/supportsSegmentationServer.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/SegmentationServices/supportsSegmentationServer.cpp.o
.PHONY : src/SegmentationServices/supportsSegmentationServer.cpp.o

src/SegmentationServices/supportsSegmentationServer.i: src/SegmentationServices/supportsSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/supportsSegmentationServer.i

# target to preprocess a source file
src/SegmentationServices/supportsSegmentationServer.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/SegmentationServices/supportsSegmentationServer.cpp.i
.PHONY : src/SegmentationServices/supportsSegmentationServer.cpp.i

src/SegmentationServices/supportsSegmentationServer.s: src/SegmentationServices/supportsSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/supportsSegmentationServer.s

# target to generate assembly for a file
src/SegmentationServices/supportsSegmentationServer.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/supportsSegmentationSrv.dir/src/SegmentationServices/supportsSegmentationServer.cpp.s
.PHONY : src/SegmentationServices/supportsSegmentationServer.cpp.s

src/obj_segmentation.o: src/obj_segmentation.cpp.o
.PHONY : src/obj_segmentation.o

# target to build an object file
src/obj_segmentation.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/src/obj_segmentation.cpp.o
.PHONY : src/obj_segmentation.cpp.o

src/obj_segmentation.i: src/obj_segmentation.cpp.i
.PHONY : src/obj_segmentation.i

# target to preprocess a source file
src/obj_segmentation.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/src/obj_segmentation.cpp.i
.PHONY : src/obj_segmentation.cpp.i

src/obj_segmentation.s: src/obj_segmentation.cpp.s
.PHONY : src/obj_segmentation.s

# target to generate assembly for a file
src/obj_segmentation.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/obj_segmentation.dir/src/obj_segmentation.cpp.s
.PHONY : src/obj_segmentation.cpp.s

src/ransac_segmentation.o: src/ransac_segmentation.cpp.o
.PHONY : src/ransac_segmentation.o

# target to build an object file
src/ransac_segmentation.cpp.o:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/src/ransac_segmentation.cpp.o
.PHONY : src/ransac_segmentation.cpp.o

src/ransac_segmentation.i: src/ransac_segmentation.cpp.i
.PHONY : src/ransac_segmentation.i

# target to preprocess a source file
src/ransac_segmentation.cpp.i:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/src/ransac_segmentation.cpp.i
.PHONY : src/ransac_segmentation.cpp.i

src/ransac_segmentation.s: src/ransac_segmentation.cpp.s
.PHONY : src/ransac_segmentation.s

# target to generate assembly for a file
src/ransac_segmentation.cpp.s:
	cd /home/luca-phd/ros_ws/src && $(MAKE) -f primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/build.make primitive_identification_tagging_and_tracking/pitt_object_table_segmentation/CMakeFiles/ransac_segmentation.dir/src/ransac_segmentation.cpp.s
.PHONY : src/ransac_segmentation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... clusterSegmentationSrv"
	@echo "... coneSegmentationSrv"
	@echo "... cylinderSegmentationSrv"
	@echo "... deepFilterSrv"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... obj_segmentation"
	@echo "... pcl_arm_filter_srv"
	@echo "... planeSegmentationSrv"
	@echo "... ransac_segmentation"
	@echo "... rebuild_cache"
	@echo "... sphereSegmentationSrv"
	@echo "... supportsSegmentationSrv"
	@echo "... test"
	@echo "... src/PCStaticProcessing/PCManager.o"
	@echo "... src/PCStaticProcessing/PCManager.i"
	@echo "... src/PCStaticProcessing/PCManager.s"
	@echo "... src/PCStaticProcessing/PCPrimitive.o"
	@echo "... src/PCStaticProcessing/PCPrimitive.i"
	@echo "... src/PCStaticProcessing/PCPrimitive.s"
	@echo "... src/SegmentationServices/clusterSegmentationServer.o"
	@echo "... src/SegmentationServices/clusterSegmentationServer.i"
	@echo "... src/SegmentationServices/clusterSegmentationServer.s"
	@echo "... src/SegmentationServices/coneSegmentationServer.o"
	@echo "... src/SegmentationServices/coneSegmentationServer.i"
	@echo "... src/SegmentationServices/coneSegmentationServer.s"
	@echo "... src/SegmentationServices/cylinderSegmentationServer.o"
	@echo "... src/SegmentationServices/cylinderSegmentationServer.i"
	@echo "... src/SegmentationServices/cylinderSegmentationServer.s"
	@echo "... src/SegmentationServices/deepFilterServer.o"
	@echo "... src/SegmentationServices/deepFilterServer.i"
	@echo "... src/SegmentationServices/deepFilterServer.s"
	@echo "... src/SegmentationServices/pcl_arm_filter_srv.o"
	@echo "... src/SegmentationServices/pcl_arm_filter_srv.i"
	@echo "... src/SegmentationServices/pcl_arm_filter_srv.s"
	@echo "... src/SegmentationServices/planeSegmentationServer.o"
	@echo "... src/SegmentationServices/planeSegmentationServer.i"
	@echo "... src/SegmentationServices/planeSegmentationServer.s"
	@echo "... src/SegmentationServices/sphereSegmentationServer.o"
	@echo "... src/SegmentationServices/sphereSegmentationServer.i"
	@echo "... src/SegmentationServices/sphereSegmentationServer.s"
	@echo "... src/SegmentationServices/supportsSegmentationServer.o"
	@echo "... src/SegmentationServices/supportsSegmentationServer.i"
	@echo "... src/SegmentationServices/supportsSegmentationServer.s"
	@echo "... src/obj_segmentation.o"
	@echo "... src/obj_segmentation.i"
	@echo "... src/obj_segmentation.s"
	@echo "... src/ransac_segmentation.o"
	@echo "... src/ransac_segmentation.i"
	@echo "... src/ransac_segmentation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/luca-phd/ros_ws/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

